/*
 * Speech to Text API v3.0
 * Speech to Text API v3.0.
 *
 * OpenAPI spec version: v3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.41
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechToTextApiV30) {
      root.SpeechToTextApiV30 = {};
    }
    root.SpeechToTextApiV30.WebHookEvents1 = factory(root.SpeechToTextApiV30.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The WebHookEvents1 model module.
   * @module model/WebHookEvents1
   * @version v3.0
   */

  /**
   * Constructs a new <code>WebHookEvents1</code>.
   * A value indicating the webhook event kinds.
   * @alias module:model/WebHookEvents1
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>WebHookEvents1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebHookEvents1} obj Optional instance to populate.
   * @return {module:model/WebHookEvents1} The populated <code>WebHookEvents1</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('datasetDeletion'))
        obj.datasetDeletion = ApiClient.convertToType(data['datasetDeletion'], 'Boolean');
      if (data.hasOwnProperty('datasetCreation'))
        obj.datasetCreation = ApiClient.convertToType(data['datasetCreation'], 'Boolean');
      if (data.hasOwnProperty('datasetProcessing'))
        obj.datasetProcessing = ApiClient.convertToType(data['datasetProcessing'], 'Boolean');
      if (data.hasOwnProperty('datasetCompletion'))
        obj.datasetCompletion = ApiClient.convertToType(data['datasetCompletion'], 'Boolean');
      if (data.hasOwnProperty('modelCreation'))
        obj.modelCreation = ApiClient.convertToType(data['modelCreation'], 'Boolean');
      if (data.hasOwnProperty('modelProcessing'))
        obj.modelProcessing = ApiClient.convertToType(data['modelProcessing'], 'Boolean');
      if (data.hasOwnProperty('modelCompletion'))
        obj.modelCompletion = ApiClient.convertToType(data['modelCompletion'], 'Boolean');
      if (data.hasOwnProperty('modelDeletion'))
        obj.modelDeletion = ApiClient.convertToType(data['modelDeletion'], 'Boolean');
      if (data.hasOwnProperty('evaluationCreation'))
        obj.evaluationCreation = ApiClient.convertToType(data['evaluationCreation'], 'Boolean');
      if (data.hasOwnProperty('evaluationProcessing'))
        obj.evaluationProcessing = ApiClient.convertToType(data['evaluationProcessing'], 'Boolean');
      if (data.hasOwnProperty('evaluationCompletion'))
        obj.evaluationCompletion = ApiClient.convertToType(data['evaluationCompletion'], 'Boolean');
      if (data.hasOwnProperty('evaluationDeletion'))
        obj.evaluationDeletion = ApiClient.convertToType(data['evaluationDeletion'], 'Boolean');
      if (data.hasOwnProperty('transcriptionCreation'))
        obj.transcriptionCreation = ApiClient.convertToType(data['transcriptionCreation'], 'Boolean');
      if (data.hasOwnProperty('transcriptionProcessing'))
        obj.transcriptionProcessing = ApiClient.convertToType(data['transcriptionProcessing'], 'Boolean');
      if (data.hasOwnProperty('transcriptionCompletion'))
        obj.transcriptionCompletion = ApiClient.convertToType(data['transcriptionCompletion'], 'Boolean');
      if (data.hasOwnProperty('transcriptionDeletion'))
        obj.transcriptionDeletion = ApiClient.convertToType(data['transcriptionDeletion'], 'Boolean');
      if (data.hasOwnProperty('endpointCreation'))
        obj.endpointCreation = ApiClient.convertToType(data['endpointCreation'], 'Boolean');
      if (data.hasOwnProperty('endpointProcessing'))
        obj.endpointProcessing = ApiClient.convertToType(data['endpointProcessing'], 'Boolean');
      if (data.hasOwnProperty('endpointCompletion'))
        obj.endpointCompletion = ApiClient.convertToType(data['endpointCompletion'], 'Boolean');
      if (data.hasOwnProperty('endpointDeletion'))
        obj.endpointDeletion = ApiClient.convertToType(data['endpointDeletion'], 'Boolean');
      if (data.hasOwnProperty('ping'))
        obj.ping = ApiClient.convertToType(data['ping'], 'Boolean');
      if (data.hasOwnProperty('challenge'))
        obj.challenge = ApiClient.convertToType(data['challenge'], 'Boolean');
    }
    return obj;
  }

  /**
   * @member {Boolean} datasetDeletion
   */
  exports.prototype.datasetDeletion = undefined;

  /**
   * @member {Boolean} datasetCreation
   */
  exports.prototype.datasetCreation = undefined;

  /**
   * @member {Boolean} datasetProcessing
   */
  exports.prototype.datasetProcessing = undefined;

  /**
   * @member {Boolean} datasetCompletion
   */
  exports.prototype.datasetCompletion = undefined;

  /**
   * @member {Boolean} modelCreation
   */
  exports.prototype.modelCreation = undefined;

  /**
   * @member {Boolean} modelProcessing
   */
  exports.prototype.modelProcessing = undefined;

  /**
   * @member {Boolean} modelCompletion
   */
  exports.prototype.modelCompletion = undefined;

  /**
   * @member {Boolean} modelDeletion
   */
  exports.prototype.modelDeletion = undefined;

  /**
   * @member {Boolean} evaluationCreation
   */
  exports.prototype.evaluationCreation = undefined;

  /**
   * @member {Boolean} evaluationProcessing
   */
  exports.prototype.evaluationProcessing = undefined;

  /**
   * @member {Boolean} evaluationCompletion
   */
  exports.prototype.evaluationCompletion = undefined;

  /**
   * @member {Boolean} evaluationDeletion
   */
  exports.prototype.evaluationDeletion = undefined;

  /**
   * @member {Boolean} transcriptionCreation
   */
  exports.prototype.transcriptionCreation = undefined;

  /**
   * @member {Boolean} transcriptionProcessing
   */
  exports.prototype.transcriptionProcessing = undefined;

  /**
   * @member {Boolean} transcriptionCompletion
   */
  exports.prototype.transcriptionCompletion = undefined;

  /**
   * @member {Boolean} transcriptionDeletion
   */
  exports.prototype.transcriptionDeletion = undefined;

  /**
   * @member {Boolean} endpointCreation
   */
  exports.prototype.endpointCreation = undefined;

  /**
   * @member {Boolean} endpointProcessing
   */
  exports.prototype.endpointProcessing = undefined;

  /**
   * @member {Boolean} endpointCompletion
   */
  exports.prototype.endpointCompletion = undefined;

  /**
   * @member {Boolean} endpointDeletion
   */
  exports.prototype.endpointDeletion = undefined;

  /**
   * @member {Boolean} ping
   */
  exports.prototype.ping = undefined;

  /**
   * @member {Boolean} challenge
   */
  exports.prototype.challenge = undefined;


  return exports;

}));
